import 'package:flutter/material.dart';

class LocalizationProvider with ChangeNotifier {
  Locale _locale = const Locale('en');
  bool _isLoading = false;

  Locale get locale => _locale;
  bool get isLoading => _isLoading;

  final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'VietSpots',
      'home': 'Home',
      'notification': 'Notification',
      'favorites': 'Favorites',
      'settings': 'Settings',
      'search_hint': 'Search places...',

      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Login to continue your journey',
      'email': 'Email',
      'password': 'Password',
      'phone_number': 'Phone Number',
      'confirm_password': 'Confirm Password',
      'create_account': 'Create Account',
      'start_journey': 'Start your journey with VietSpots',
      'email_required': 'Email is required',
      'phone_required': 'Phone number is required',
      'password_required': 'Password is required',
      'confirm_password_required': 'Confirm password is required',
      'passwords_do_not_match': 'Passwords do not match',
      'register': 'Register',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'dont_have_account': "Don't have an account? ",

      'forgot_password_title': 'Forgot Password',
      'forgot_password_desc':
          'Enter your email address to receive a verification code.',
      'send_code': 'Send Code',
      'verify_code_title': 'Verify Code',
      'code_sent_to': 'Code sent to',
      'otp_code': 'OTP Code',
      'verify': 'Verify',
      'reset_password_title': 'Reset Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'password_changed_success': 'Password changed successfully',
      'change_password': 'Change Password',

      'permissions_required_title': 'Permissions Required',
      'permissions_required_desc':
          'To provide the best travel recommendations, we need access to your location.',
      'location_required': 'Location (Required)',
      'location_required_to_continue':
          'Location permission is required to continue.',
      'allow': 'Allow',
      'get_started': 'Get Started',

      'photo_permission_required': 'Photo permission is required.',
      'avatar_updated': 'Avatar updated',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'save': 'Save',
      'save_changes': 'Save Changes',
      'general_information': 'General Information',
      'private_information': 'Private Information',
      'settings_section_personal_information': 'Personal Information',
      'settings_section_security_permissions': 'Security & Permissions',
      'settings_section_general': 'General',
      'settings_section_about': 'About',
      'preferences': 'Preferences',
      'preferences_subtitle': 'Adventure, relaxing, ...',
      'culture': 'Culture',
      'culture_subtitle': 'Select your culture',
      'religion_subtitle': 'Select your religion',
      'companion_preference': 'Companion Preference',

      'current_password': 'Current Password',
      'update_password': 'Update Password',
      'update_password_success': 'Update Password Successfully',
      'all_fields_required': 'All fields are required.',
      'current_password_incorrect': 'Current password is incorrect.',
      'new_passwords_do_not_match': 'New passwords do not match.',

      'permissions': 'Permissions',
      'location_access': 'Location Access',
      'notifications': 'Notifications',
      'photo_gallery': 'Photo Gallery',
      'location_permission_denied': 'Location permission denied.',
      'notification_permission_denied': 'Notification permission denied.',
      'photo_permission_denied': 'Photo permission denied.',

      'help_center': 'Help Center',
      'help_center_body': 'Content is being updated.',
      'legal_policy': 'Legal Policy',
      'legal_policy_body': 'Content is being updated.',

      'pref_adventure': 'Adventure',
      'pref_less_travelling': 'Less travelling',
      'pref_beautiful': 'Beautiful',
      'pref_mysterious': 'Mysterious',
      'pref_food': 'Food',
      'pref_culture': 'Culture',
      'pref_nature': 'Nature',
      'pref_nightlife': 'Nightlife',

      'culture_vietnamese': 'Vietnamese',
      'culture_chinese': 'Chinese',
      'culture_japanese': 'Japanese',
      'culture_korean': 'Korean',
      'culture_thai': 'Thai',
      'culture_indian': 'Indian',
      'culture_western_european': 'Western / European',
      'culture_american': 'American',
      'culture_middle_eastern': 'Middle Eastern',
      'culture_african': 'African',

      'religion_none': 'None',
      'religion_buddhism': 'Buddhism',
      'religion_christianity': 'Christianity',
      'religion_islam': 'Islam',
      'religion_hinduism': 'Hinduism',
      'religion_judaism': 'Judaism',
      'religion_sikhism': 'Sikhism',

      'companion_solo': 'Solo',
      'companion_couple': 'Couple',
      'companion_family': 'Family',
      'companion_friends': 'Friends',

      'recommended_for_you': 'Recommended for you',
      'nearby_places': 'Nearby places',
      'places_you_visited': 'Places you visited',

      'notification_details': 'Notification Details',

      'distance': 'Distance',
      'estimated_time': 'Estimated time',
      'start': 'Start',
      'start_navigation_placeholder': 'Start navigation (placeholder)',

      'open': 'Open',
      'share': 'Share',
      'delete': 'Delete',

      'edit_profile': 'Edit Profile',
      'change_avatar': 'Change Avatar',
      'full_name': 'Full Name',
      'full_name_required': 'Full Name is required',
      'next': 'Next',

      'tell_us_about_you': 'Tell us about you',
      'religion': 'Religion',
      'religion_required': 'Religion is required.',
      'your_hobby': 'Your hobby',
      'travel_companion': 'Who do you travel with?',
      'finish': 'Finish',

      'favorites_title': 'Favorites',
      'no_favorites_yet': 'No favorites yet',
      'favorites_empty_hint':
          'Start exploring and save your\nfavorite places here',
      'explore_places': 'Explore Places',
      'notif_system_update_title': 'System Update',
      'notif_system_update_subtitle':
          'VietSpots 2.0 is now available with new AI features!',
      'notif_system_update_time': '2 hours ago',
      'notif_new_suggestion_title': 'New Suggestion',
      'notif_new_suggestion_subtitle':
          'Based on your recent trip to Da Lat, you might like...',
      'notif_new_suggestion_time': '1 day ago',
      'notif_welcome_title': 'Welcome to VietSpots',
      'notif_welcome_subtitle':
          'Thanks for joining our community of travelers.',
      'notif_welcome_time': '3 days ago',

      'remove_favorite_title': 'Remove from favorites?',
      'remove_favorite_body':
          'Are you sure you want to remove this place from favorites?',

      'added_to_favorites': 'Added to Favorites',
      'removed_from_favorites': 'Removed from Favorites',
      'highlights': 'Highlights',

      'add_comment': 'Add Comment',
      'get_directions': 'Get Directions',
      'location': 'Location',
      'price': 'Price',
      'opening_time': 'Opening time',
      'about_this_place': 'About this place',
      'rating': 'Rating',
      'reviews': 'reviews',
      'no_reviews_yet': 'No reviews yet.',
      'add_review': 'Add Review',
      'review_hint': 'Write your review...',
      'review_required': 'Review text is required',
      'attach_image': 'Attach Image',
      'submit': 'Submit',
      'review_added': 'Review added',
      'could_not_open_website': 'Could not open website',

      'chat_hint': 'Ask TourMate...',
      'chat_greeting': 'Hi there!',
      'chat_intro':
          'Ask TourMate for sightseeing suggestions\nbased on your needs.',
      'typing': 'VietSpots is typing',
      'ai_name': 'VietSpots AI',
      'ai_subtitle': 'Your Personal Travel Assistant',
      'close_chat': 'Close Chat',
      'new_chat': 'New Chat',
      'new_chat_started': 'New chat started',
      'history': 'History',
      'no_conversations_yet': 'No conversations yet',
      'start_chatting_history': 'Start chatting to build history',
      'share_not_implemented': 'Share not implemented',
      'conversation_deleted': 'Conversation deleted',

      'done': 'Done',
      'could_not_crop_image': 'Could not crop image',

      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'language_english': 'English',
      'language_vietnamese': 'Tiếng Việt',
      'language_russian': 'Русский',
      'language_chinese': '中文',
      'logout': 'Log Out',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'yes': 'Yes',
    },
    'vi': {
      'app_name': 'VietSpots',
      'home': 'Trang chủ',
      'notification': 'Thông báo',
      'favorites': 'Yêu thích',
      'settings': 'Cài đặt',
      'search_hint': 'Tìm kiếm địa điểm...',

      'welcome_back': 'Chào mừng trở lại',
      'login_subtitle': 'Đăng nhập để tiếp tục hành trình',
      'email': 'Email',
      'password': 'Mật khẩu',
      'phone_number': 'Số điện thoại',
      'confirm_password': 'Xác nhận mật khẩu',
      'create_account': 'Tạo tài khoản',
      'start_journey': 'Bắt đầu hành trình cùng VietSpots',
      'email_required': 'Vui lòng nhập email',
      'phone_required': 'Vui lòng nhập số điện thoại',
      'password_required': 'Vui lòng nhập mật khẩu',
      'confirm_password_required': 'Vui lòng xác nhận mật khẩu',
      'passwords_do_not_match': 'Mật khẩu không khớp',
      'register': 'Đăng ký',
      'forgot_password': 'Quên mật khẩu?',
      'login': 'Đăng nhập',
      'sign_up': 'Đăng ký',
      'dont_have_account': 'Chưa có tài khoản? ',

      'forgot_password_title': 'Quên mật khẩu',
      'forgot_password_desc': 'Nhập email để nhận mã xác minh.',
      'send_code': 'Gửi mã',
      'verify_code_title': 'Xác minh mã',
      'code_sent_to': 'Đã gửi mã đến',
      'otp_code': 'Mã OTP',
      'verify': 'Xác minh',
      'reset_password_title': 'Đặt lại mật khẩu',
      'new_password': 'Mật khẩu mới',
      'confirm_new_password': 'Xác nhận mật khẩu mới',
      'password_changed_success': 'Đổi mật khẩu thành công',
      'change_password': 'Đổi mật khẩu',

      'permissions_required_title': 'Yêu cầu quyền truy cập',
      'permissions_required_desc':
          'Để gợi ý du lịch tốt hơn, chúng tôi cần quyền truy cập vị trí của bạn.',
      'location_required': 'Vị trí (Bắt buộc)',
      'location_required_to_continue': 'Cần quyền vị trí để tiếp tục.',
      'allow': 'Cho phép',
      'get_started': 'Bắt đầu',

      'photo_permission_required': 'Cần quyền truy cập ảnh.',
      'avatar_updated': 'Đã cập nhật ảnh đại diện',
      'age': 'Tuổi',
      'gender': 'Giới tính',
      'male': 'Nam',
      'female': 'Nữ',
      'other': 'Khác',
      'save': 'Lưu',
      'save_changes': 'Lưu thay đổi',
      'general_information': 'Thông tin chung',
      'private_information': 'Thông tin riêng tư',
      'settings_section_personal_information': 'Thông tin cá nhân',
      'settings_section_security_permissions': 'Bảo mật & quyền truy cập',
      'settings_section_general': 'Chung',
      'settings_section_about': 'Giới thiệu',
      'preferences': 'Sở thích',
      'preferences_subtitle': 'Phiêu lưu, thư giãn, ...',
      'culture': 'Văn hóa',
      'culture_subtitle': 'Chọn văn hóa của bạn',
      'religion_subtitle': 'Chọn tôn giáo của bạn',
      'companion_preference': 'Bạn đồng hành',

      'current_password': 'Mật khẩu hiện tại',
      'update_password': 'Cập nhật mật khẩu',
      'update_password_success': 'Cập nhật mật khẩu thành công',
      'all_fields_required': 'Vui lòng điền đầy đủ thông tin.',
      'current_password_incorrect': 'Mật khẩu hiện tại không đúng.',
      'new_passwords_do_not_match': 'Mật khẩu mới không khớp.',

      'permissions': 'Quyền truy cập',
      'location_access': 'Truy cập vị trí',
      'notifications': 'Thông báo',
      'photo_gallery': 'Thư viện ảnh',
      'location_permission_denied': 'Từ chối quyền vị trí.',
      'notification_permission_denied': 'Từ chối quyền thông báo.',
      'photo_permission_denied': 'Từ chối quyền ảnh.',

      'help_center': 'Trung tâm trợ giúp',
      'help_center_body': 'Nội dung đang được cập nhật.',
      'legal_policy': 'Chính sách pháp lý',
      'legal_policy_body': 'Nội dung đang được cập nhật.',

      'pref_adventure': 'Phiêu lưu',
      'pref_less_travelling': 'Ít di chuyển',
      'pref_beautiful': 'Đẹp',
      'pref_mysterious': 'Bí ẩn',
      'pref_food': 'Ẩm thực',
      'pref_culture': 'Văn hóa',
      'pref_nature': 'Thiên nhiên',
      'pref_nightlife': 'Cuộc sống về đêm',

      'culture_vietnamese': 'Việt Nam',
      'culture_chinese': 'Trung Quốc',
      'culture_japanese': 'Nhật Bản',
      'culture_korean': 'Hàn Quốc',
      'culture_thai': 'Thái Lan',
      'culture_indian': 'Ấn Độ',
      'culture_western_european': 'Phương Tây / Châu Âu',
      'culture_american': 'Mỹ',
      'culture_middle_eastern': 'Trung Đông',
      'culture_african': 'Châu Phi',

      'religion_none': 'Không',
      'religion_buddhism': 'Phật giáo',
      'religion_christianity': 'Thiên Chúa giáo',
      'religion_islam': 'Hồi giáo',
      'religion_hinduism': 'Ấn Độ giáo',
      'religion_judaism': 'Do Thái giáo',
      'religion_sikhism': 'Đạo Sikh',

      'companion_solo': 'Một mình',
      'companion_couple': 'Cặp đôi',
      'companion_family': 'Gia đình',
      'companion_friends': 'Bạn bè',

      'recommended_for_you': 'Gợi ý cho bạn',
      'nearby_places': 'Địa điểm gần đây',
      'places_you_visited': 'Địa điểm bạn đã ghé',

      'notification_details': 'Chi tiết thông báo',

      'distance': 'Khoảng cách',
      'estimated_time': 'Thời gian ước tính',
      'start': 'Bắt đầu',
      'start_navigation_placeholder': 'Bắt đầu điều hướng (mô phỏng)',

      'open': 'Mở',
      'share': 'Chia sẻ',
      'delete': 'Xóa',

      'edit_profile': 'Chỉnh sửa hồ sơ',
      'change_avatar': 'Đổi ảnh đại diện',
      'full_name': 'Họ và tên',
      'full_name_required': 'Vui lòng nhập họ và tên',
      'next': 'Tiếp theo',

      'tell_us_about_you': 'Cho chúng tôi biết về bạn',
      'religion': 'Tôn giáo',
      'religion_required': 'Vui lòng chọn tôn giáo.',
      'your_hobby': 'Sở thích',
      'travel_companion': 'Bạn thường đi cùng ai?',
      'finish': 'Hoàn tất',

      'favorites_title': 'Yêu thích',
      'no_favorites_yet': 'Chưa có mục yêu thích',
      'favorites_empty_hint':
          'Bắt đầu khám phá và lưu\nnhững địa điểm yêu thích tại đây',
      'explore_places': 'Khám phá địa điểm',
      'notif_system_update_title': 'Cập nhật hệ thống',
      'notif_system_update_subtitle':
          'VietSpots 2.0 hiện đã có với các tính năng AI mới!',
      'notif_system_update_time': '2 giờ trước',
      'notif_new_suggestion_title': 'Gợi ý mới',
      'notif_new_suggestion_subtitle':
          'Dựa trên chuyến đi gần đây của bạn đến Đà Lạt, bạn có thể thích...',
      'notif_new_suggestion_time': '1 ngày trước',
      'notif_welcome_title': 'Chào mừng đến với VietSpots',
      'notif_welcome_subtitle':
          'Cảm ơn bạn đã tham gia cộng đồng du lịch của chúng tôi.',
      'notif_welcome_time': '3 ngày trước',

      'remove_favorite_title': 'Xóa khỏi yêu thích?',
      'remove_favorite_body':
          'Bạn có chắc muốn xóa địa điểm này khỏi danh sách yêu thích không?',

      'added_to_favorites': 'Đã thêm vào yêu thích',
      'removed_from_favorites': 'Đã xóa khỏi yêu thích',
      'highlights': 'Điểm nổi bật',

      'add_comment': 'Thêm đánh giá',
      'get_directions': 'Chỉ đường',
      'location': 'Vị trí',
      'price': 'Giá',
      'opening_time': 'Giờ mở cửa',
      'about_this_place': 'Giới thiệu',
      'rating': 'Đánh giá',
      'reviews': 'đánh giá',
      'no_reviews_yet': 'Chưa có đánh giá.',
      'add_review': 'Thêm đánh giá',
      'review_hint': 'Viết đánh giá của bạn...',
      'review_required': 'Vui lòng nhập nội dung đánh giá',
      'attach_image': 'Đính kèm ảnh',
      'submit': 'Gửi',
      'review_added': 'Đã thêm đánh giá',
      'could_not_open_website': 'Không thể mở website',

      'chat_hint': 'Hỏi TourMate...',
      'chat_greeting': 'Xin chào!',
      'chat_intro': 'Hỏi TourMate gợi ý địa điểm\nphù hợp nhu cầu của bạn.',
      'typing': 'VietSpots đang trả lời',
      'ai_name': 'VietSpots AI',
      'ai_subtitle': 'Trợ lý du lịch cá nhân của bạn',
      'close_chat': 'Đóng chat',
      'new_chat': 'Cuộc trò chuyện mới',
      'new_chat_started': 'Đã bắt đầu chat mới',
      'history': 'Lịch sử',
      'no_conversations_yet': 'Chưa có cuộc trò chuyện',
      'start_chatting_history': 'Bắt đầu chat để lưu lịch sử',
      'share_not_implemented': 'Chưa hỗ trợ chia sẻ',
      'conversation_deleted': 'Đã xóa cuộc trò chuyện',

      'done': 'Xong',
      'could_not_crop_image': 'Không thể cắt ảnh',

      'dark_mode': 'Chế độ tối',
      'language': 'Ngôn ngữ',
      'language_english': 'English',
      'language_vietnamese': 'Tiếng Việt',
      'language_russian': 'Русский',
      'language_chinese': '中文',
      'logout': 'Đăng xuất',
      'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất?',
      'cancel': 'Hủy',
      'yes': 'Có',
    },
    'ru': {
      'app_name': 'VietSpots',
      'home': 'Главная',
      'notification': 'Уведомления',
      'favorites': 'Избранное',
      'settings': 'Настройки',
      'search_hint': 'Поиск мест...',

      'welcome_back': 'С возвращением',
      'login_subtitle': 'Войдите, чтобы продолжить',
      'email': 'Email',
      'password': 'Пароль',
      'phone_number': 'Телефон',
      'confirm_password': 'Подтвердите пароль',
      'create_account': 'Создать аккаунт',
      'start_journey': 'Начните путешествие с VietSpots',
      'email_required': 'Требуется Email',
      'phone_required': 'Требуется номер телефона',
      'password_required': 'Требуется пароль',
      'confirm_password_required': 'Требуется подтверждение пароля',
      'passwords_do_not_match': 'Пароли не совпадают',
      'register': 'Зарегистрироваться',
      'forgot_password': 'Забыли пароль?',
      'login': 'Войти',
      'sign_up': 'Регистрация',
      'dont_have_account': 'Нет аккаунта? ',

      'forgot_password_title': 'Забыли пароль',
      'forgot_password_desc':
          'Введите email, чтобы получить код подтверждения.',
      'send_code': 'Отправить код',
      'verify_code_title': 'Проверка кода',
      'code_sent_to': 'Код отправлен на',
      'otp_code': 'OTP код',
      'verify': 'Проверить',
      'reset_password_title': 'Сброс пароля',
      'new_password': 'Новый пароль',
      'confirm_new_password': 'Подтвердите новый пароль',
      'password_changed_success': 'Пароль успешно изменен',
      'change_password': 'Сменить пароль',

      'permissions_required_title': 'Нужны разрешения',
      'permissions_required_desc':
          'Чтобы давать лучшие рекомендации, нужен доступ к геопозиции.',
      'location_required': 'Геолокация (обязательно)',
      'location_required_to_continue':
          'Для продолжения требуется разрешение на геолокацию.',
      'allow': 'Разрешить',
      'get_started': 'Начать',

      'photo_permission_required': 'Требуется доступ к фото.',
      'avatar_updated': 'Аватар обновлён',
      'age': 'Возраст',
      'gender': 'Пол',
      'male': 'Мужской',
      'female': 'Женский',
      'other': 'Другое',
      'save': 'Сохранить',
      'save_changes': 'Сохранить изменения',
      'general_information': 'Общая информация',
      'private_information': 'Личная информация',
      'settings_section_personal_information': 'Личная информация',
      'settings_section_security_permissions': 'Безопасность и разрешения',
      'settings_section_general': 'Общие',
      'settings_section_about': 'О приложении',
      'preferences': 'Предпочтения',
      'preferences_subtitle': 'Приключения, отдых, ...',
      'culture': 'Культура',
      'culture_subtitle': 'Выберите вашу культуру',
      'religion_subtitle': 'Выберите вашу религию',
      'companion_preference': 'Спутник',

      'current_password': 'Текущий пароль',
      'update_password': 'Обновить пароль',
      'update_password_success': 'Пароль успешно обновлён',
      'all_fields_required': 'Все поля обязательны.',
      'current_password_incorrect': 'Текущий пароль неверный.',
      'new_passwords_do_not_match': 'Новые пароли не совпадают.',

      'permissions': 'Разрешения',
      'location_access': 'Доступ к местоположению',
      'notifications': 'Уведомления',
      'photo_gallery': 'Галерея фото',
      'location_permission_denied': 'Доступ к местоположению отклонён.',
      'notification_permission_denied': 'Доступ к уведомлениям отклонён.',
      'photo_permission_denied': 'Доступ к фото отклонён.',

      'help_center': 'Центр помощи',
      'help_center_body': 'Содержимое обновляется.',
      'legal_policy': 'Правовая политика',
      'legal_policy_body': 'Содержимое обновляется.',

      'pref_adventure': 'Приключения',
      'pref_less_travelling': 'Меньше поездок',
      'pref_beautiful': 'Красивое',
      'pref_mysterious': 'Таинственное',
      'pref_food': 'Еда',
      'pref_culture': 'Культура',
      'pref_nature': 'Природа',
      'pref_nightlife': 'Ночная жизнь',

      'culture_vietnamese': 'Вьетнамская',
      'culture_chinese': 'Китайская',
      'culture_japanese': 'Японская',
      'culture_korean': 'Корейская',
      'culture_thai': 'Тайская',
      'culture_indian': 'Индийская',
      'culture_western_european': 'Западная / Европейская',
      'culture_american': 'Американская',
      'culture_middle_eastern': 'Ближневосточная',
      'culture_african': 'Африканская',

      'religion_none': 'Нет',
      'religion_buddhism': 'Буддизм',
      'religion_christianity': 'Христианство',
      'religion_islam': 'Ислам',
      'religion_hinduism': 'Индуизм',
      'religion_judaism': 'Иудаизм',
      'religion_sikhism': 'Сикхизм',

      'companion_solo': 'Один',
      'companion_couple': 'Пара',
      'companion_family': 'Семья',
      'companion_friends': 'Друзья',

      'recommended_for_you': 'Рекомендуем',
      'nearby_places': 'Рядом',
      'places_you_visited': 'Вы посещали',

      'notification_details': 'Детали уведомления',

      'distance': 'Расстояние',
      'estimated_time': 'Оценка времени',
      'start': 'Старт',
      'start_navigation_placeholder': 'Запуск навигации (заглушка)',

      'open': 'Открыть',
      'share': 'Поделиться',
      'delete': 'Удалить',

      'edit_profile': 'Редактировать профиль',
      'change_avatar': 'Сменить аватар',
      'full_name': 'Полное имя',
      'full_name_required': 'Требуется полное имя',
      'next': 'Далее',

      'tell_us_about_you': 'Расскажите о себе',
      'religion': 'Религия',
      'religion_required': 'Требуется религия.',
      'your_hobby': 'Хобби',
      'travel_companion': 'С кем вы путешествуете?',
      'finish': 'Готово',

      'favorites_title': 'Избранное',
      'no_favorites_yet': 'Пока нет избранного',
      'favorites_empty_hint':
          'Начните исследовать и сохранять ваши\nлюбимые места здесь',
      'explore_places': 'Исследовать места',
      'notif_system_update_title': 'Системное обновление',
      'notif_system_update_subtitle':
          'VietSpots 2.0 теперь доступен с новыми AI функциями!',
      'notif_system_update_time': '2 часа назад',
      'notif_new_suggestion_title': 'Новое предложение',
      'notif_new_suggestion_subtitle':
          'На основе вашей недавней поездки в Да Лат, вам может понравиться...',
      'notif_new_suggestion_time': '1 день назад',
      'notif_welcome_title': 'Добро пожаловать в VietSpots',
      'notif_welcome_subtitle':
          'Спасибо, что присоединились к нашему сообществу путешественников.',
      'notif_welcome_time': '3 дня назад',

      'remove_favorite_title': 'Удалить из избранного?',
      'remove_favorite_body':
          'Вы уверены, что хотите удалить это место из избранного?',

      'added_to_favorites': 'Добавлено в избранное',
      'removed_from_favorites': 'Удалено из избранного',
      'highlights': 'Особенности',

      'add_comment': 'Добавить отзыв',
      'get_directions': 'Маршрут',
      'location': 'Местоположение',
      'price': 'Цена',
      'opening_time': 'Часы работы',
      'about_this_place': 'О месте',
      'rating': 'Рейтинг',
      'reviews': 'отзывов',
      'no_reviews_yet': 'Пока нет отзывов.',
      'add_review': 'Добавить отзыв',
      'review_hint': 'Напишите отзыв...',
      'review_required': 'Текст отзыва обязателен',
      'attach_image': 'Прикрепить фото',
      'submit': 'Отправить',
      'review_added': 'Отзыв добавлен',
      'could_not_open_website': 'Не удалось открыть сайт',

      'chat_hint': 'Спросить TourMate...',
      'chat_greeting': 'Привет!',
      'chat_intro': 'Спросите TourMate о местах\nпо вашим предпочтениям.',
      'typing': 'VietSpots печатает',
      'ai_name': 'VietSpots AI',
      'ai_subtitle': 'Ваш личный помощник путешествий',
      'close_chat': 'Закрыть чат',
      'new_chat': 'Новый чат',
      'new_chat_started': 'Новый чат начат',
      'history': 'История',
      'no_conversations_yet': 'Пока нет диалогов',
      'start_chatting_history': 'Начните чат, чтобы появилась история',
      'share_not_implemented': 'Поделиться не реализовано',
      'conversation_deleted': 'Диалог удален',

      'done': 'Готово',
      'could_not_crop_image': 'Не удалось обрезать изображение',

      'dark_mode': 'Темный режим',
      'language': 'Язык',
      'language_english': 'English',
      'language_vietnamese': 'Tiếng Việt',
      'language_russian': 'Русский',
      'language_chinese': '中文',
      'logout': 'Выйти',
      'logout_confirm': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'yes': 'Да',
    },
    'zh': {
      'app_name': 'VietSpots',
      'home': '首页',
      'notification': '通知',
      'favorites': '收藏',
      'settings': '设置',
      'search_hint': '搜索地点...',

      'welcome_back': '欢迎回来',
      'login_subtitle': '登录以继续旅程',
      'email': '邮箱',
      'password': '密码',
      'phone_number': '手机号',
      'confirm_password': '确认密码',
      'create_account': '创建账号',
      'start_journey': '和 VietSpots 一起开始旅程',
      'email_required': '必须填写邮箱',
      'phone_required': '必须填写手机号',
      'password_required': '必须填写密码',
      'confirm_password_required': '必须确认密码',
      'passwords_do_not_match': '两次密码不一致',
      'register': '注册',
      'forgot_password': '忘记密码？',
      'login': '登录',
      'sign_up': '注册',
      'dont_have_account': '没有账号？',

      'forgot_password_title': '忘记密码',
      'forgot_password_desc': '输入邮箱以获取验证码。',
      'send_code': '发送验证码',
      'verify_code_title': '验证验证码',
      'code_sent_to': '验证码已发送至',
      'otp_code': '验证码',
      'verify': '验证',
      'reset_password_title': '重置密码',
      'new_password': '新密码',
      'confirm_new_password': '确认新密码',
      'password_changed_success': '密码修改成功',
      'change_password': '修改密码',

      'permissions_required_title': '需要权限',
      'permissions_required_desc': '为了更好的推荐，需要访问你的位置信息。',
      'location_required': '位置（必需）',
      'location_required_to_continue': '需要位置权限才能继续。',
      'allow': '允许',
      'get_started': '开始使用',

      'photo_permission_required': '需要相册权限。',
      'avatar_updated': '头像已更新',
      'age': '年龄',
      'gender': '性别',
      'male': '男',
      'female': '女',
      'other': '其他',
      'save': '保存',
      'save_changes': '保存更改',
      'general_information': '基本信息',
      'private_information': '隐私信息',
      'settings_section_personal_information': '个人信息',
      'settings_section_security_permissions': '安全与权限',
      'settings_section_general': '通用',
      'settings_section_about': '关于',
      'preferences': '偏好',
      'preferences_subtitle': '冒险、放松、...',
      'culture': '文化',
      'culture_subtitle': '选择你的文化',
      'religion_subtitle': '选择你的宗教',
      'companion_preference': '同行偏好',

      'current_password': '当前密码',
      'update_password': '更新密码',
      'update_password_success': '密码更新成功',
      'all_fields_required': '所有字段均为必填。',
      'current_password_incorrect': '当前密码不正确。',
      'new_passwords_do_not_match': '新密码不一致。',

      'permissions': '权限',
      'location_access': '位置访问',
      'notifications': '通知',
      'photo_gallery': '相册',
      'location_permission_denied': '位置权限被拒绝。',
      'notification_permission_denied': '通知权限被拒绝。',
      'photo_permission_denied': '相册权限被拒绝。',

      'help_center': '帮助中心',
      'help_center_body': '内容正在更新。',
      'legal_policy': '法律政策',
      'legal_policy_body': '内容正在更新。',

      'pref_adventure': '冒险',
      'pref_less_travelling': '少出行',
      'pref_beautiful': '美景',
      'pref_mysterious': '神秘',
      'pref_food': '美食',
      'pref_culture': '文化',
      'pref_nature': '自然',
      'pref_nightlife': '夜生活',

      'culture_vietnamese': '越南',
      'culture_chinese': '中国',
      'culture_japanese': '日本',
      'culture_korean': '韩国',
      'culture_thai': '泰国',
      'culture_indian': '印度',
      'culture_western_european': '西方 / 欧洲',
      'culture_american': '美国',
      'culture_middle_eastern': '中东',
      'culture_african': '非洲',

      'religion_none': '无',
      'religion_buddhism': '佛教',
      'religion_christianity': '基督教',
      'religion_islam': '伊斯兰教',
      'religion_hinduism': '印度教',
      'religion_judaism': '犹太教',
      'religion_sikhism': '锡克教',

      'companion_solo': '独自',
      'companion_couple': '情侣',
      'companion_family': '家庭',
      'companion_friends': '朋友',

      'recommended_for_you': '为你推荐',
      'nearby_places': '附近地点',
      'places_you_visited': '你去过的地方',

      'notification_details': '通知详情',

      'distance': '距离',
      'estimated_time': '预计时间',
      'start': '开始',
      'start_navigation_placeholder': '开始导航（占位）',

      'open': '打开',
      'share': '分享',
      'delete': '删除',

      'edit_profile': '编辑资料',
      'change_avatar': '更换头像',
      'full_name': '姓名',
      'full_name_required': '需要填写姓名',
      'next': '下一步',

      'tell_us_about_you': '介绍一下你',
      'religion': '宗教',
      'religion_required': '必须选择宗教。',
      'your_hobby': '爱好',
      'travel_companion': '你和谁一起旅行？',
      'finish': '完成',

      'favorites_title': '收藏',
      'no_favorites_yet': '暂无收藏',
      'favorites_empty_hint': '开始探索并保存您最喜欢的地方',
      'explore_places': '探索地点',
      'notif_system_update_title': '系统更新',
      'notif_system_update_subtitle': 'VietSpots 2.0 现已推出新 AI 功能！',
      'notif_system_update_time': '2小时前',
      'notif_new_suggestion_title': '新建议',
      'notif_new_suggestion_subtitle': '根据您最近的达拉特之行，您可能会喜欢...',
      'notif_new_suggestion_time': '1天前',
      'notif_welcome_title': '欢迎来到 VietSpots',
      'notif_welcome_subtitle': '感谢您加入我们的旅行者社区。',
      'notif_welcome_time': '3天前',

      'remove_favorite_title': '从收藏移除？',
      'remove_favorite_body': '确定要从收藏中移除这个地点吗？',

      'added_to_favorites': '已添加到收藏',
      'removed_from_favorites': '已从收藏中移除',
      'highlights': '亮点',

      'add_comment': '添加评价',
      'get_directions': '路线',
      'location': '位置',
      'price': '价格',
      'opening_time': '营业时间',
      'about_this_place': '关于这里',
      'rating': '评分',
      'reviews': '条评价',
      'no_reviews_yet': '暂无评价。',
      'add_review': '添加评价',
      'review_hint': '写下你的评价...',
      'review_required': '评价内容不能为空',
      'attach_image': '添加图片',
      'submit': '提交',
      'review_added': '评价已添加',
      'could_not_open_website': '无法打开网站',

      'chat_hint': '询问 TourMate...',
      'chat_greeting': '你好！',
      'chat_intro': '向 TourMate 询问\n符合你需求的景点推荐。',
      'typing': 'VietSpots 正在输入',
      'ai_name': 'VietSpots AI',
      'ai_subtitle': '你的专属旅行助手',
      'close_chat': '关闭聊天',
      'new_chat': '新聊天',
      'new_chat_started': '已开始新聊天',
      'history': '历史',
      'no_conversations_yet': '暂无对话',
      'start_chatting_history': '开始聊天以生成历史记录',
      'share_not_implemented': '分享未实现',
      'conversation_deleted': '对话已删除',

      'done': '完成',
      'could_not_crop_image': '无法裁剪图片',

      'dark_mode': '深色模式',
      'language': '语言',
      'language_english': 'English',
      'language_vietnamese': 'Tiếng Việt',
      'language_russian': 'Русский',
      'language_chinese': '中文',
      'logout': '登出',
      'logout_confirm': '您确定要登出吗？',
      'cancel': '取消',
      'yes': '是',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }

  Future<void> setLanguage(String languageCode) async {
    _isLoading = true;
    notifyListeners();

    // Simulate loading delay
    await Future.delayed(const Duration(seconds: 3));

    _locale = Locale(languageCode);
    _isLoading = false;
    notifyListeners();
  }
}
